name: Docker Image Build and Push
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            atarrio/powpeg-node
            ghcr.io/atarrio/powpeg-node
          tags: |
            type=ref,event=tag
            type=edge
            # This is used for generating IRIS-3 out of IRIS-3.x.y.
            type=match,pattern=(\w+-\d+)\.\d+\.\d+.*,group=1

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GitHub container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: RSK_RELEASE=${{ steps.vars.outputs.tag }}
